#!/usr/bin/env python
"""Run arena shards on a Kaggle kernel and pull the archives back.

One job = one kernel = one batch session (CPU: ~4 vCPU, 12 h). Jobs are
independent, so N of them is N x that. The kernel copies the read-only dataset
into /kaggle/working, runs the shard commands in parallel, and leaves
`out/arena/**` + `out/logs/**` where `kaggle kernels output` can fetch them.

    # define a job as a shard command template and a shard count
    python -X utf8 scripts/kaggle/launch.py push --job ctl0 --shards 4 \\
        --cmd 'scripts/arena.py play "bc:a,net=out/policy_v5_s2.npz" "bc:b,net=out/policy_v5_s2.npz" --deck-a grimmsnarl --deck-b grimmsnarl --matches 250 --archive out/arena/ctl0/s{i}.jsonl'

    python -X utf8 scripts/kaggle/launch.py status --job ctl0
    python -X utf8 scripts/kaggle/launch.py pull   --job ctl0

⚠ `{i}` in --cmd is the shard index and MUST appear in the --archive path.
Six processes appending to one archive is the failure E18 called out; the
launcher refuses a command whose archive is not shard-unique.

⚠ Shard commands get no seed. `battle_start` takes none (§8bw), so shards do
not replay each other -- but that also means a job is not reproducible by
re-running it. The archives are the record.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STAGE = ROOT / "out" / "kaggle_jobs"
USER = "siamrahman29"
CODE_DS = f"{USER}/ptcg-code-v1"

RUNNER = '''# auto-generated by scripts/kaggle/launch.py -- job {job}
import json, os, shutil, subprocess, sys, time, zipfile
from pathlib import Path

REPO = Path("/kaggle/working/repo")
CMDS = {cmds!r}
THEN = {then!r}
COLLECT = {collect!r}
OUTFLAG = {outflag!r}

t0 = time.time()
print("cpu_count =", os.cpu_count(), flush=True)

# 🔴 Do NOT hardcode /kaggle/input/<slug>. Kaggle has mounted this dataset at
# `/kaggle/input/datasets/...` rather than `/kaggle/input/ptcg-code-v1`, and a
# hardcoded path fails in under a second with a message that looks like "the
# dataset is missing" when it is present under another name. FIND the payload.
IN = Path("/kaggle/input")
SRC = None
for cand in IN.rglob("ptcg_code.zip"):
    SRC = cand.parent
    break
if SRC is None:
    for cand in IN.rglob("src/ptcg"):
        SRC = cand.parents[1]
        break
if SRC is None:
    tree = [str(p.relative_to(IN)) for p in IN.rglob("*") if p.is_dir()][:40]
    sys.exit(f"payload not found under /kaggle/input; dirs seen: {{tree}}")
print("payload found at", SRC, flush=True)
shutil.copytree(SRC, REPO, dirs_exist_ok=True)
# The dataset is ONE archive whose member paths are already repo-relative, so
# it extracts at the repo root. Kaggle sometimes expands an uploaded zip on
# ingest and sometimes does not -- handle both rather than guess.
for z in list(REPO.glob("*.zip")):
    with zipfile.ZipFile(z) as zf:
        zf.extractall(REPO)
    z.unlink()
    print("extracted", z.name, flush=True)
missing = [p for p in ("src/ptcg", "scripts/arena.py", "agents/sa", "decks",
                       "data/sample_submission") if not (REPO / p).exists()]
if missing:
    print("TREE:", sorted(p.name for p in REPO.iterdir()), flush=True)
    sys.exit(f"payload incomplete, missing: {{missing}}")
t_unpack = time.time()
(REPO / "out" / "logs").mkdir(parents=True, exist_ok=True)
for c in CMDS:
    Path(REPO / c.split(OUTFLAG)[1].split()[0]).parent.mkdir(parents=True, exist_ok=True)

env = dict(os.environ, PYTHONPATH=f"{{REPO}}/src:{{REPO}}/agents:{{REPO}}", PYTHONUNBUFFERED="1")
procs = []
for i, c in enumerate(CMDS):
    log = open(REPO / "out" / "logs" / f"{job}_s{{i}}.txt", "w")
    procs.append((i, subprocess.Popen([sys.executable, "-X", "utf8"] + c.split(),
                                      cwd=REPO, env=env, stdout=log, stderr=subprocess.STDOUT), log))
    print(f"launched shard {{i}}", flush=True)

rc = 0
for i, p, log in procs:
    p.wait(); log.close()
    print(f"shard {{i}} exit={{p.returncode}} t={{time.time()-t0:.0f}}s", flush=True)
    rc |= p.returncode

# receipts: the arena prints its own seat-corrected score -- never re-derive it
for i, _, _ in procs:
    txt = (REPO / "out" / "logs" / f"{job}_s{{i}}.txt").read_text(errors="replace")
    tail = [l for l in txt.splitlines() if "score=" in l or "Traceback" in l]
    print(f"--- shard {{i}} ---"); print("\\n".join(tail[-6:]) or "(no score line)", flush=True)

# A post-command runs ONCE, after every shard, in the same kernel. This is what
# lets generation and training share a job: a self-play corpus is gigabytes and
# a trained net is megabytes, so training HERE and pulling only the net is the
# difference between a feasible round and a download that outlasts the session.
if THEN and rc == 0:
    log = open(REPO / "out" / "logs" / f"{job}_then.txt", "w")
    print("running --then:", THEN, flush=True)
    p = subprocess.Popen([sys.executable, "-X", "utf8"] + THEN.split(),
                         cwd=REPO, env=env, stdout=log, stderr=subprocess.STDOUT)
    p.wait(); log.close()
    rc |= p.returncode
    print(f"then exit={{p.returncode}} t={{time.time()-t0:.0f}}s", flush=True)
    tail = (REPO / "out" / "logs" / f"{job}_then.txt").read_text(errors="replace")
    print("--- then (tail) ---"); print("\\n".join(tail.splitlines()[-25:]), flush=True)
elif THEN:
    print(f"SKIPPING --then: a shard failed (rc={{rc}}); a post-command over a "
          f"partial corpus would train on silently truncated data", flush=True)

out = Path("/kaggle/working")
missing = []
for sub in COLLECT:
    s = REPO / sub
    if s.exists():
        shutil.copytree(s, out / sub, dirs_exist_ok=True)
    else:
        # 🔴 A MISSING COLLECT DIR IS A LOST JOB, NOT A SKIPPED COPY. E27
        # round 2 ran to completion on Kaggle -- 8,000 games, V, advantages,
        # a fine-tune -- and returned 0.0 MB, because the payload held a
        # PRE-PATCH driver that wrote to out/ while --collect looked in
        # out/e27. Version skew between the pushed dataset and the local
        # tree, which is rule 20 one layer out. Say so loudly.
        missing.append(sub)
        print(f"🔴 collect: {{sub}} DOES NOT EXIST -- nothing to pull from it",
              flush=True)
# What the job PRODUCED but nobody is collecting -- checked while the tree
# still exists, because one line later it is deleted and the evidence with it.
# ⚠ mtime > t_unpack is what makes this specific: the payload itself unpacks
# ~40 nets into out/, and flagging those would make every job exit 64. copytree
# and zip extraction both preserve the original mtimes, so only files this run
# WROTE are newer than the moment unpacking finished.
lost = sorted(str(f.relative_to(REPO)) for f in (REPO / "out").rglob("*.npz")
              if f.stat().st_mtime > t_unpack
              and not any(str(f.relative_to(REPO)).startswith(c) for c in COLLECT))
if lost:
    print(f"🔴 {{len(lost)}} .npz PRODUCED AND NOT COLLECTED -- this job is "
          f"about to throw them away: {{lost[:8]}}", flush=True)
    rc |= 64
shutil.rmtree(REPO, ignore_errors=True)
rows = sum(1 for f in (out / "out/arena").rglob("*.jsonl") for _ in f.open()) \\
    if (out / "out/arena").exists() else 0
mb = sum(f.stat().st_size for f in out.rglob("*") if f.is_file()) / 1e6
print(f"=== job {job} done rc={{rc}} rows={{rows}} out={{mb:.1f}}MB wall={{time.time()-t0:.0f}}s ===")
sys.exit(rc)
'''


def job_dir(job: str) -> Path:
    return STAGE / job


def push(args: argparse.Namespace) -> None:
    # The guard is the one E18 paid for -- six processes appending to one file --
    # and it is kept for every job type, not just arena play. What generalises is
    # only WHICH flag names the per-shard output.
    if args.out_flag not in args.cmd:
        sys.exit(f"--cmd must contain {args.out_flag} (a shard needs its own "
                 f"output path; pass --out-flag for a different one)")
    if "{i}" not in args.cmd.split(args.out_flag)[1].split()[0]:
        sys.exit(f"the {args.out_flag} path must contain {{i}} -- shards must "
                 f"not share an output")
    if args.then and "{i}" in args.then:
        sys.exit("--then runs ONCE after all shards, so {i} is undefined in it")

    cmds = [args.cmd.replace("{i}", str(i)) for i in range(args.shards)]
    collect = [c.strip() for c in args.collect.split(",") if c.strip()]
    d = job_dir(args.job)
    d.mkdir(parents=True, exist_ok=True)
    (d / "run.py").write_text(
        RUNNER.format(job=args.job, cmds=cmds, then=args.then,
                      collect=collect, outflag=args.out_flag),
        encoding="utf-8")
    (d / "kernel-metadata.json").write_text(json.dumps({
        "id": f"{USER}/ptcg-{args.job}",
        "title": f"ptcg-{args.job}",
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": args.gpu,
        "enable_internet": False,
        "dataset_sources": [CODE_DS],
        "competition_sources": [],
        "kernel_sources": [],
    }, indent=2), encoding="utf-8")

    print(f"=== job {args.job}: {args.shards} shards ===")
    for c in cmds[:2]:
        print("  " + c)
    if len(cmds) > 2:
        print(f"  ... and {len(cmds)-2} more")
    if args.dry_run:
        print(f"\n(dry run -- kernel staged at {d})")
        return
    r = subprocess.run(["kaggle", "kernels", "push", "-p", str(d)],
                       capture_output=True, text=True)
    print(r.stdout or r.stderr)
    sys.exit(r.returncode)


def status(args: argparse.Namespace) -> None:
    r = subprocess.run(["kaggle", "kernels", "status", f"{USER}/ptcg-{args.job}"],
                       capture_output=True, text=True)
    print(r.stdout or r.stderr)


def pull(args: argparse.Namespace) -> None:
    dest = ROOT / "out" / "kaggle_out" / args.job
    dest.mkdir(parents=True, exist_ok=True)
    r = subprocess.run(["kaggle", "kernels", "output", f"{USER}/ptcg-{args.job}",
                        "-p", str(dest)], capture_output=True, text=True)
    print(r.stdout or r.stderr)
    rows = 0
    for f in dest.rglob("*.jsonl"):
        n = sum(1 for _ in f.open(encoding="utf-8", errors="replace"))
        rows += n
        print(f"  {n:6d} rows  {f.relative_to(dest)}")
    print(f"=== {rows} rows pulled to {dest} ===")


def main() -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="mode", required=True)

    p = sub.add_parser("push")
    p.add_argument("--job", required=True)
    p.add_argument("--cmd", required=True, help="shard command; {i} = shard index")
    p.add_argument("--shards", type=int, default=4)
    p.add_argument("--gpu", action="store_true")
    p.add_argument("--out-flag", default="--archive",
                   help="the flag naming each shard's own output path "
                        "(--archive for arena.py, --out for the generators)")
    p.add_argument("--then", default="",
                   help="one command run ONCE after every shard succeeds, in "
                        "the same kernel -- e.g. train on what the shards just "
                        "generated, so only the net is pulled back")
    p.add_argument("--collect", default="out/arena,out/logs",
                   help="comma-separated repo-relative dirs copied to "
                        "/kaggle/working for `pull`")
    p.add_argument("--dry-run", action="store_true")
    p.set_defaults(fn=push)

    for name, fn in (("status", status), ("pull", pull)):
        q = sub.add_parser(name)
        q.add_argument("--job", required=True)
        q.set_defaults(fn=fn)

    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
