"""Import the four sample rule-based agents from `notebooks/` into the repo.

Each `a-sample-rule-based-agent-*.ipynb` bundles a self-contained Kaggle agent
(`agent(obs_dict) -> list[int]`) plus its own 60-card deck. This script lifts the
agent body out, verbatim except for the deck.csv loader, so the arena can run it:

  * agents/agentkit/rulebased/sources/<name>.py -- the agent body, byte-for-byte
    from the notebook except the deck.csv loader, which is swapped for
    `my_deck = list(MY_DECK)` so the arena can inject the dealt deck.

Decks: iono / mega_abomasnow_ex / mega_lucario_ex in `decks/` already match their
notebooks byte-for-byte, so they are only re-verified here. The dragapult notebook
deck differs from the reconstructed `decks/dragapult_ex.py`, so that file is
overwritten with the notebook-exact 60 cards (each rule agent must play the deck
it was tuned for -- it hardcodes its own card ids for card counting).

Re-run this whenever the notebooks change. It is idempotent.
"""
from __future__ import annotations

import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
NB_DIR = ROOT / "notebooks"
SRC_DIR = ROOT / "agents" / "agentkit" / "rulebased" / "sources"
DECK_DIR = ROOT / "decks"

# short name -> (notebook file, decks/ module name)
NOTEBOOKS = {
    "dragapult": ("a-sample-rule-based-agent-dragapult-ex-deck.ipynb", "dragapult_ex"),
    "iono": ("a-sample-rule-based-agent-iono-s-deck.ipynb", "iono"),
    "abomasnow": ("a-sample-rule-based-agent-mega-abomasnow-ex-deck.ipynb", "mega_abomasnow_ex"),
    "lucario": ("a-sample-rule-based-agent-mega-lucario-ex-deck.ipynb", "mega_lucario_ex"),
}
# Decks are generated from the notebooks; overwrite (or create) them all.
OVERWRITE_DECK = {"dragapult", "iono", "abomasnow", "lucario"}

# The deck.csv loader is byte-identical across all four notebooks; replace it
# with an injection point the arena fills via the exec namespace.
DECK_LOAD_RE = re.compile(
    r"# Load deck\.csv.*?my_deck\.append\(int\(csv\[i\]\)\)\n", re.S)
DECK_LOAD_REPL = "my_deck = list(MY_DECK)  # injected by agentkit.rulebased\n"

# A decklist constant line: `Name = <cardId>  # x<count>` (the "x" is a mojibaked
# multiplication sign in most rows, a literal "x" in a few). Lines without a
# trailing count (e.g. `use_support = 0`) are not deck cards.
CARD_RE = re.compile(r"^([A-Za-z_]\w*)\s*=\s*(\d+)\s*#[^\d]*(\d+)\s*$")


def _writefile_cell(nb_path: Path) -> str:
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    for cell in nb["cells"]:
        if cell["cell_type"] == "code":
            src = "".join(cell["source"])
            if "writefile main.py" in src:
                return src
    raise SystemExit(f"no `%%writefile main.py` cell in {nb_path.name}")


def parse_deck(src: str) -> list[tuple[str, int, int]]:
    """(constant name, card id, count) for each decklist line, notebook order."""
    cards: list[tuple[str, int, int]] = []
    for line in src.splitlines():
        m = CARD_RE.match(line)
        if not m:
            continue
        name, card_id, count = m.group(1), int(m.group(2)), int(m.group(3))
        if card_id <= 0 or not (1 <= count <= 40):
            continue
        cards.append((name, card_id, count))
    total = sum(c for _, _, c in cards)
    if total != 60:
        raise SystemExit(f"parsed deck sums to {total}, not 60: {cards}")
    return cards


def strip_source(src: str) -> str:
    """Notebook cell -> importable agent body (verbatim but for the deck loader)."""
    lines = src.splitlines(keepends=True)
    if lines and lines[0].lstrip().startswith("%%writefile"):
        lines = lines[1:]  # drop the Jupyter magic
    body = "".join(lines)
    body, n = DECK_LOAD_RE.subn(DECK_LOAD_REPL, body)
    if n != 1:
        raise SystemExit(f"expected exactly one deck.csv loader, found {n}")
    return body


DECK_TEMPLATE = '''"""Dragapult ex deck for the sample rule-based agent.

Auto-generated by scripts/import_rule_agents.py from
notebooks/{nb} -- the exact 60-card deck the
rule agent was tuned for (it hardcodes these card ids for card counting).
Do not hand-edit; re-run the importer instead.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/{mod}.py`
    from base import Deck  # noqa: F401

{consts}

DECKLIST: dict[int, int] = {{
{entries}
}}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {{DECK.size}}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{{entry.count:>2}}x  {{entry.card.name}}")
'''


def write_deck(mod: str, nb: str, cards: list[tuple[str, int, int]]) -> None:
    consts = "\n".join(f"{name} = {cid}" for name, cid, _ in cards)
    entries = "\n".join(f"    {name}: {cnt}," for name, _, cnt in cards)
    text = DECK_TEMPLATE.format(nb=nb, mod=mod, consts=consts, entries=entries)
    (DECK_DIR / f"{mod}.py").write_text(text, encoding="utf-8")


def verify_deck(mod: str, cards: list[tuple[str, int, int]]) -> None:
    parsed = {cid: cnt for _, cid, cnt in cards}
    existing = importlib.import_module(f"decks.{mod}").DECKLIST
    if parsed != existing:
        raise SystemExit(
            f"decks/{mod}.py no longer matches its notebook; add '{mod}' to "
            f"OVERWRITE_DECK or reconcile by hand.\n  notebook: {parsed}\n"
            f"  decks/  : {existing}")


def main() -> int:
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    for name, (nb, mod) in NOTEBOOKS.items():
        src = _writefile_cell(NB_DIR / nb)
        cards = parse_deck(src)
        if name in OVERWRITE_DECK:
            write_deck(mod, nb, cards)
            action = f"deck decks/{mod}.py OVERWRITTEN"
        else:
            verify_deck(mod, cards)
            action = f"deck decks/{mod}.py verified"
        (SRC_DIR / f"{name}.py").write_text(strip_source(src), encoding="utf-8")
        print(f"  {name}: {action}; agent sources/{name}.py ({len(cards)} cards)")
    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
