"""Lift the public Crustle agent into `rule:crustle` + `decks/crustle_v1`.

Source: `pixiux/ptcg-crustle-v1-submit` (pulled to `notebooks/pulled/`), whose
`main.py` is embedded in the notebook as a gzip+base64 blob. 422 lines of
readable option scoring, no external deps beyond `cg.api`.

**Why this matters (2026-07-30):** Crustle went from 1 seat in 1,600 to 18.1% of
the field at a 56.6% win rate, with the LB's top two players on it, while our own
win rate fell 52.2% -> 47.5% (HANDOFF §1). Every rule in this repo was A/B'd
against `lucario_v10`, which is now **0%** of the meta. A competent Crustle
opponent is therefore the single most valuable piece of arena infrastructure we
can add -- and `bc` cannot supply it: `bc` piloting the Crispin toolbox lost
0.089/1.000 (we scored **0.911**), i.e. an off-distribution pilot gives an anchor
so weak the A/B has no room to resolve anything.

The agent plays the actual lockdown: bench Dwebble, evolve to Crustle, arm 3
energies including Grass, attach Hero's Cape, set Battle Cage as the stadium,
heal with Jumbo Ice Cream / Cook whenever damage >= 50, retreat to a ready
Crustle, and attack with Superb Scissors (479, 120 damage) or Ascension (478).

Idempotent: rerun after re-pulling the notebook.

    python -X utf8 scripts/import_crustle_agent.py
"""
from __future__ import annotations

import base64
import gzip
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks" / "pulled" / "ptcg-crustle-v1-submit.py"
AGENT_OUT = ROOT / "agents" / "agentkit" / "rulebased" / "sources" / "crustle.py"
DECK_OUT = ROOT / "decks" / "crustle_v1.py"

HEADER = '''"""Crustle pilot -- imported verbatim from `pixiux/ptcg-crustle-v1-submit`.

Generated by `scripts/import_crustle_agent.py`; do not edit by hand. The only
change from the notebook's `main.py` is the deck constant: the original builds
`MY_DECK` from its own card lists, and `make_rule_agent` injects the deck the
arena was asked for, so the assignment is replaced with `MY_DECK = list(MY_DECK)`
to consume the injected value.
"""
'''

DECK_TEMPLATE = '''"""The Crustle pilot's own 60 -- `pixiux/ptcg-crustle-v1-submit`.

Generated by `scripts/import_crustle_agent.py`; do not edit by hand.

**This is the deck `rule:crustle` was tuned for**, so it is the list to use when
you want the strongest Crustle we can run locally:
`rule:crustle --deck-b crustle_v1`. It differs from `decks/crustle.py`, which is
the *field consensus* list mined from 2026-07-29 top episodes (seen 77x). Use
`crustle.py` to ask "what do we actually face" and `crustle_v1.py` to ask "how
bad is this matchup against a pilot that executes the lockdown". A pilot run on
the other list scores ~20 of its cards through a generic fallback, so it plays
them legally but badly -- worth remembering before reading a matchup number.
"""

from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # pragma: no cover
    from base import Deck  # noqa: F401


DECKLIST: dict[int, int] = {
%s}

DECK = Deck(DECKLIST)
assert DECK.size == 60, DECK.size
'''


def main() -> int:
    if not NOTEBOOK.exists():
        print(f"missing {NOTEBOOK}\n"
              "pull it first:\n"
              "  python -X utf8 -c \"from kaggle.api.kaggle_api_extended import "
              "KaggleApi; a=KaggleApi(); a.authenticate(); "
              "a.kernels_pull('pixiux/ptcg-crustle-v1-submit', "
              "path='notebooks/pulled', metadata=False)\"", file=sys.stderr)
        return 1

    src = NOTEBOOK.read_text(encoding="utf-8")
    blob = re.search(r'MAIN_GZ_B64 = """(.*?)"""', src, re.S)
    deck_text = re.search(r'DECK_TEXT = """(.*?)"""', src, re.S)
    if not blob or not deck_text:
        print("could not find MAIN_GZ_B64 / DECK_TEXT in the notebook",
              file=sys.stderr)
        return 1

    code = gzip.decompress(base64.b64decode(blob.group(1).strip())).decode("utf-8")

    # Replace the agent's own deck construction with the injected deck.
    pattern = re.compile(r"^MY_DECK = \(\n(?:.*?\n)*?\)\n", re.M)
    if not pattern.search(code):
        print("MY_DECK block not found -- notebook layout changed", file=sys.stderr)
        return 1
    code = pattern.sub("MY_DECK = list(MY_DECK)  # injected by make_rule_agent\n",
                       code, count=1)

    AGENT_OUT.write_text(HEADER + "\n" + code, encoding="utf-8")
    print(f"wrote {AGENT_OUT.relative_to(ROOT)} ({len(code.splitlines())} lines)")

    counts = Counter(int(x) for x in deck_text.group(1).split())
    if sum(counts.values()) != 60:
        print(f"deck is {sum(counts.values())} cards, not 60", file=sys.stderr)
        return 1

    sys.path.insert(0, str(ROOT))
    try:
        from decks.base import card_table
        names = {cid: (info.name if info else "?")
                 for cid, info in ((c, card_table().get(c)) for c in counts)}
    except Exception:  # noqa: BLE001
        names = {cid: "" for cid in counts}

    lines = "".join(
        f"    {cid}: {n},{' ' * max(1, 6 - len(str(cid)) - len(str(n)))}"
        f"# {names.get(cid, '')}\n".replace(" #  ", " # ")
        for cid, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))
    DECK_OUT.write_text(DECK_TEMPLATE % lines, encoding="utf-8")
    print(f"wrote {DECK_OUT.relative_to(ROOT)} ({len(counts)} distinct, 60 cards)")

    print("\nregister it (agents/agentkit/rulebased/__init__.py DECK_MODULE):"
          '\n    "crustle": "crustle_v1",'
          "\n\nthen:\n  python -X utf8 scripts/arena.py play bc rule:crustle "
          "--deck-a grimmsnarl --deck-b crustle_v1 --matches 200")
    return 0


if __name__ == "__main__":
    sys.exit(main())
