"""Lift the Alakazam and Archaludon pilots out of `notebooks/` into `rule:*`.

**Why (2026-07-31, and it is HANDOFF rule 16's fix).** `p9_field_census.py`
named the field we actually play in, from 109 real ladder games:

    Alakazam                22.0%   we win 66.7%
    Marnie's Grimmsnarl ex  13.8%   60.0%   <- mirror, have it
    Crustle                 12.8%   57.1%   <- `rule:crustle`, have it
    Mega Lucario ex         12.8%   50.0%   <- `rule:v10`, have it (wrongly retired)
    Archaludon ex           10.1%   45.5%   <- our WORST matchup
                            -----
    top 5                   71.6% of the field

The two we could not A/B against were the **largest** archetype and the one we
**lose to most**. Both pilots were sitting checked into `notebooks/` unused:

  * `rule-based-not-psychic-alakazam-best-5th.ipynb` -- the author reports 5th
    place, pure rules, no ML, no search. Its own `deck.csv` matches our
    24-game reconstruction of the field's Alakazam list card for card.
  * `a-sample-archaludon-75-wr-vs-my-1300-starmie.ipynb` -- a scored-option
    Archaludon/Cinderace pilot.

⚠ Rule 12's clause still binds: **an anchor must be COMPETITIVE to resolve
anything.** These two are the best available, but their strength against us is
an empirical question -- read the head-to-head score before trusting any delta
measured through them, exactly as `rule:crustle`'s 0.663 was checked.

Each notebook's `main.py` is embedded as a plain code cell; the only edit is the
`deck.csv` loader, replaced with the deck `make_rule_agent` injects. Idempotent.

    python -X utf8 scripts/import_field_agents.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "agents" / "agentkit" / "rulebased" / "sources"
DECKS = ROOT / "decks"

DECK_TEMPLATE = '''"""%(title)s

Generated by `scripts/import_field_agents.py`; do not edit by hand -- this is
the pilot's own 60, lifted from the notebook's `deck.csv`.

%(why)s
"""

from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # pragma: no cover
    from base import Deck  # noqa: F401


DECKLIST: dict[int, int] = {
%(lines)s}

DECK = Deck(DECKLIST)
assert DECK.size == 60, DECK.size
'''


class Job:
    def __init__(self, name, notebook, code_cell, deck_cell, patch, header,
                 deck_module, deck_title, deck_why):
        self.name = name
        self.notebook = notebook
        self.code_cell = code_cell
        self.deck_cell = deck_cell
        self.patch = patch          # (compiled regex, replacement)
        self.header = header
        self.deck_module = deck_module
        self.deck_title = deck_title
        self.deck_why = deck_why


JOBS = [
    Job(
        name="alakazam5",
        notebook="rule-based-not-psychic-alakazam-best-5th.ipynb",
        code_cell=3,
        deck_cell=2,
        # The loader is a bare module-level block, not a function.
        patch=(re.compile(
            r'^# Load deck\.csv in the dataset\n(?:.*\n)*?'
            r'^    my_deck\.append\(int\(csv\[i\]\)\)\n', re.M),
            "my_deck = list(MY_DECK)  # injected by make_rule_agent\n"),
        header='''"""Alakazam pilot -- imported verbatim from the public notebook
`rule-based-not-psychic-alakazam-best-5th` (author reports **5th place**, pure
rules, no ML, no search).

Generated by `scripts/import_field_agents.py`; do not edit by hand. The only
change is the `deck.csv` loader block, replaced with `my_deck = list(MY_DECK)`
so `make_rule_agent` can inject the deck the arena was asked for.

**This is the anchor for the field's LARGEST archetype (22.0% of 109 real
ladder games, `out/logs/p9_field_census_pooled.txt`).** The deck attacks with
Alakazam's Powerful Hand -- 20 damage per card in hand -- behind a draw engine
of Kadabra/Alakazam Psychic Draw, Dudunsparce's Run Away Draw and Fezandipiti
ex's Flip the Script, so its damage output scales with its hand size. Nothing
in `targeting.py` reasons about that.
"""
''',
        deck_module="alakazam5",
        deck_title="The 5th-place Alakazam pilot's own 60.",
        deck_why=(
            "**This is the deck `rule:alakazam5` was tuned for.** It also\n"
            "matches the field: `p9_field_census.py` reconstructed the Alakazam\n"
            "list from 24 real ladder games and every card it could see is in\n"
            "here at the same count (Abra x4, Kadabra x3-4, Alakazam x3,\n"
            "Dunsparce x3, Dudunsparce x2, Fezandipiti ex x1, Telepath Psychic\n"
            "Energy x4, Rare Candy x3-4, Poke Pad x4, Buddy-Buddy Poffin x4).\n"
            "`decks/alakazam.py` is the older reconstruction -- prefer this one."),
    ),
    Job(
        name="archaludon",
        notebook="a-sample-archaludon-75-wr-vs-my-1300-starmie.ipynb",
        code_cell=1,
        deck_cell=2,
        patch=(re.compile(
            r'^def read_deck_csv\(\):\n(?:^    .*\n|^\n)+', re.M),
            'def read_deck_csv():\n'
            '    return list(MY_DECK)  # injected by make_rule_agent\n'),
        header='''"""Archaludon ex + Cinderace pilot -- imported verbatim from the public
notebook `a-sample-archaludon-75-wr-vs-my-1300-starmie`.

Generated by `scripts/import_field_agents.py`; do not edit by hand. The only
change is `read_deck_csv()`, whose body becomes `return list(MY_DECK)` so
`make_rule_agent` can inject the deck the arena was asked for.

**This is the anchor for our WORST measured matchup**: 10.1% of 109 real ladder
games and we won only 45.5% of them (`out/logs/p9_field_census_pooled.txt`).
Metal Defender is 220 for {M}{M}{M} with "no Weakness next turn", Hero's Cape
puts Archaludon ex at 400 HP, and Full Metal Lab takes 30 off every attack into
a Metal Pokemon -- i.e. it is a second damage-reduction deck, and the only one
`chip_target`'s wall branch does NOT know about (`WALL_POKEMON = {345}`).
"""
''',
        deck_module="archaludon_ex",
        deck_title="The Archaludon ex + Cinderace pilot's own 60.",
        deck_why=(
            "**This is the deck `rule:archaludon` was tuned for**, and it is\n"
            "close to the field's list: `p9_field_census.py` reconstructed 11\n"
            "real games and saw Duraludon x3, Archaludon ex x3, Cinderace x3,\n"
            "Relicanth x1, Basic {M} x8+, Full Metal Lab x4, Lillie's\n"
            "Determination x4, Explorer's Guidance x4."),
    ),
]


def do(job: Job) -> int:
    nb_path = ROOT / "notebooks" / job.notebook
    if not nb_path.exists():
        print(f"missing {nb_path}", file=sys.stderr)
        return 1
    nb = json.loads(nb_path.read_text(encoding="utf-8"))

    code = "".join(nb["cells"][job.code_cell]["source"])
    code = re.sub(r"^%%writefile main\.py\n", "", code)
    pattern, repl = job.patch
    if not pattern.search(code):
        print(f"{job.name}: deck loader not found -- notebook layout changed",
              file=sys.stderr)
        return 1
    code = pattern.sub(repl, code, count=1)
    if "MY_DECK" not in code:
        print(f"{job.name}: patch did not introduce MY_DECK", file=sys.stderr)
        return 1

    out = SOURCES / f"{job.name}.py"
    out.write_text(job.header + "\n" + code, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(code.splitlines())} lines)")

    deck_src = "".join(nb["cells"][job.deck_cell]["source"])
    deck_src = re.sub(r"^%%writefile deck\.csv\n", "", deck_src)
    counts = Counter(int(x) for x in deck_src.split())
    if sum(counts.values()) != 60:
        print(f"{job.name}: deck is {sum(counts.values())} cards, not 60",
              file=sys.stderr)
        return 1

    sys.path.insert(0, str(ROOT))
    try:
        from decks.base import card_table
        names = {cid: (info.name if info else "?")
                 for cid, info in ((c, card_table().get(c)) for c in counts)}
    except Exception:  # noqa: BLE001
        names = {cid: "" for cid in counts}

    lines = "".join(
        f"    {cid}: {n},{' ' * max(1, 6 - len(str(cid)) - len(str(n)))}"
        f"# {names.get(cid, '')}\n".replace(" #  ", " # ")
        for cid, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))
    deck_out = DECKS / f"{job.deck_module}.py"
    deck_out.write_text(DECK_TEMPLATE % {"title": job.deck_title,
                                         "why": job.deck_why,
                                         "lines": lines}, encoding="utf-8")
    print(f"wrote {deck_out.relative_to(ROOT)} "
          f"({len(counts)} distinct, 60 cards)")
    return 0


def main() -> int:
    rc = 0
    for job in JOBS:
        rc |= do(job)
    print("\nregistered names (agents/agentkit/rulebased/__init__.py):")
    for job in JOBS:
        print(f'    "{job.name}": "{job.deck_module}",')
    print("\nthen, per anchor:\n"
          "  python -X utf8 scripts/arena.py play bc rule:alakazam5 "
          "--deck-a grimmsnarl --deck-b alakazam5 --matches 1000")
    return rc


if __name__ == "__main__":
    sys.exit(main())
