"""Import the public `Baseline Agent V10 | LB 950+` notebook into the repo.

Why: every opponent in our arena is one of kiyotah's *sample* rule agents, and
the live leaderboard now says those sit around 743 -- the same place we do. A
yardstick we cannot beat is worthless. This notebook is a public agent measured
at LB 950+, i.e. ~200 points above anything we have ever played against.

It is imported the same way as `import_rule_agents.py` does the samples: the
`%%writefile main.py` cell verbatim, except the deck.csv round-trip is replaced
with `my_deck = list(MY_DECK)` so the arena can inject the dealt deck.

  agents/agentkit/rulebased/sources/v10.py   the agent body
  decks/lucario_v10.py                       its exact 60 cards

Its deck is *not* `decks/mega_lucario_ex.py` -- V10 retuned the list (4 Riolu,
3 Boss's Orders, 14 energy, 2 Poke Pad against the sample's 3/2/13/4). It
hardcodes card ids for counting, so it must be dealt its own list.

Re-run whenever the notebook changes. Idempotent.
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks" / "strong-start-baseline-agent-v10-lb-950.ipynb"
SRC = ROOT / "agents" / "agentkit" / "rulebased" / "sources" / "v10.py"
DECK = ROOT / "decks" / "lucario_v10.py"

# The notebook writes deck.csv from a literal DECK list, then reads it back.
# Replace the whole round-trip with the arena's injection point.
DECK_BLOCK_RE = re.compile(
    r"^DECK = \[.*?^Path\(\"deck\.csv\"\)\.write_text\([^\n]*\n", re.S | re.M)
LOADER_RE = re.compile(
    r"^DECK_PATH = \"deck\.csv\".*?my_deck = \[int\(line\).*?\]\n",
    re.S | re.M)
DECK_LITERAL_RE = re.compile(r"^DECK = \[(.*?)\]", re.S | re.M)

CARD_NAMES = {
    673: "Makuhita", 674: "Hariyama", 675: "Lunatone", 676: "Solrock",
    677: "Riolu", 678: "Mega_Lucario_ex", 6: "Basic_Fighting_Energy",
    1102: "Dusk_Ball", 1123: "Switch", 1141: "Premium_Power_Pro",
    1142: "Fighting_Gong", 1152: "Poke_Pad", 1159: "Hero_Cape",
    1182: "Boss_Orders", 1192: "Carmine", 1227: "Lillie_Determination",
    1252: "Gravity_Mountain",
}


def _writefile_cell(nb_path: Path) -> str:
    """The `%%writefile main.py` cell body, magic line stripped."""
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    for cell in nb["cells"]:
        if cell["cell_type"] != "code":
            continue
        src = "".join(cell["source"])
        if src.lstrip().startswith("%%writefile main.py"):
            return src.split("\n", 1)[1]
    raise SystemExit(f"no `%%writefile main.py` cell in {nb_path}")


def _emit_deck(cards: list[int]) -> str:
    counts = Counter(cards)
    unknown = sorted(set(counts) - set(CARD_NAMES))
    if unknown:
        raise SystemExit(f"unnamed card ids {unknown}; add them to CARD_NAMES")
    order = sorted(counts, key=lambda cid: CARD_NAMES[cid])
    consts = "\n".join(f"{CARD_NAMES[cid]} = {cid}" for cid in order)
    entries = "\n".join(f"    {CARD_NAMES[cid]}: {counts[cid]}," for cid in order)
    return f'''"""V10 baseline's Mega Lucario ex list (public LB 950+ notebook).

Auto-generated by scripts/import_v10_agent.py from
notebooks/strong-start-baseline-agent-v10-lb-950.ipynb. This is NOT the sample
agent's mega_lucario_ex list -- V10 retuned it, and the agent hardcodes these
card ids for counting. Do not hand-edit; re-run the importer.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/lucario_v10.py`
    from base import Deck  # noqa: F401

{consts}

DECKLIST: dict[int, int] = {{
{entries}
}}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {{DECK.size}}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{{entry.count:>2}}x  {{entry.card.name}}")
'''


def main() -> int:
    body = _writefile_cell(NB)

    lit = DECK_LITERAL_RE.search(body)
    if lit is None:
        raise SystemExit("no DECK literal in the notebook cell")
    cards = [int(tok) for tok in re.findall(r"\d+", lit.group(1))]
    if len(cards) != 60:
        raise SystemExit(f"expected 60 cards, parsed {len(cards)}")

    body, n_block = DECK_BLOCK_RE.subn("", body)
    body, n_load = LOADER_RE.subn(
        "my_deck = list(MY_DECK)  # injected by agentkit.rulebased\n", body)
    if (n_block, n_load) != (1, 1):
        raise SystemExit(f"deck plumbing not matched (block={n_block} "
                         f"loader={n_load}); the notebook changed shape")
    if "deck.csv" in body:
        raise SystemExit("a deck.csv reference survived the rewrite")

    SRC.write_text(body, encoding="utf-8")
    DECK.write_text(_emit_deck(cards), encoding="utf-8")
    print(f"wrote {SRC.relative_to(ROOT)} ({len(body)} bytes)")
    print(f"wrote {DECK.relative_to(ROOT)} ({len(set(cards))} unique cards)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
