"""The 5th-place Alakazam pilot's own 60.

Generated by `scripts/import_field_agents.py`; do not edit by hand -- this is
the pilot's own 60, lifted from the notebook's `deck.csv`.

**This is the deck `rule:alakazam5` was tuned for**, and it is the
field's deck where it counts. `p9_field_census.py` reconstructed
the Alakazam list from 24 real ladder games: the ENGINE matches
exactly (Abra x4, Kadabra x3-4, Alakazam x3, Dunsparce x3,
Dudunsparce x2, Fezandipiti ex x1, Telepath Psychic Energy x4,
Poke Pad x4, Buddy-Buddy Poffin x4, Dawn x4, Hilda x3-4), while 7
of 23 observed cards differ and all 7 are tech slots -- notably
the field plays Nighttime Mine as a stadium and this pilot does
not, so stadium contests read weak through this anchor.
⚠ Do NOT retune it toward the reconstruction: the reconstruction
pools 24 different players, and a pilot scoring cards it was not
written for plays them badly (see `crustle_v1` vs `crustle`).
`decks/alakazam.py` is the older reconstruction -- prefer this one.
"""

from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # pragma: no cover
    from base import Deck  # noqa: F401


DECKLIST: dict[int, int] = {
    19: 4,   # Telepath Psychic Energy
    741: 4,  # Abra
    742: 4,  # Kadabra
    1086: 4, # Buddy-Buddy Poffin
    1152: 4, # Poké Pad
    1225: 4, # Hilda
    1231: 4, # Dawn
    1264: 4, # Battle Cage
    305: 3,  # Dunsparce
    743: 3,  # Alakazam
    1079: 3, # Rare Candy
    1081: 3, # Enhanced Hammer
    1156: 3, # Lucky Helmet
    5: 2,    # Basic {P} Energy
    66: 2,   # Dudunsparce
    1182: 2, # Boss’s Orders
    13: 1,   # Enriching Energy
    140: 1,  # Fezandipiti ex
    142: 1,  # Genesect
    343: 1,  # Shaymin
    858: 1,  # Psyduck
    1097: 1, # Night Stretcher
    1129: 1, # Sacred Ash
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, DECK.size
