"""The Archaludon ex + Cinderace pilot's own 60.

Generated by `scripts/import_field_agents.py`; do not edit by hand -- this is
the pilot's own 60, lifted from the notebook's `deck.csv`.

**This is the deck `rule:archaludon` was tuned for**, and it is
close to the field's list: `p9_field_census.py` reconstructed 11
real games and saw Duraludon x3, Archaludon ex x3, Cinderace x3,
Relicanth x1, Basic {M} x8+, Full Metal Lab x4, Lillie's
Determination x4, Explorer's Guidance x4.
"""

from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # pragma: no cover
    from base import Deck  # noqa: F401


DECKLIST: dict[int, int] = {
    8: 11,   # Basic {M} Energy
    169: 4,  # Duraludon
    190: 4,  # Archaludon ex
    666: 4,  # Cinderace
    1121: 4, # Ultra Ball
    1122: 4, # Pokégear 3.0
    1147: 4, # Jumbo Ice Cream
    1152: 4, # Poké Pad
    1182: 4, # Boss’s Orders
    1185: 4, # Explorer’s Guidance
    1227: 4, # Lillie's Determination
    1244: 4, # Full Metal Lab
    1097: 3, # Night Stretcher
    57: 1,   # Relicanth
    1159: 1, # Hero’s Cape
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, DECK.size
