"""The Crustle pilot's own 60 -- `pixiux/ptcg-crustle-v1-submit`.

Generated by `scripts/import_crustle_agent.py`; do not edit by hand.

**This is the deck `rule:crustle` was tuned for**, so it is the list to use when
you want the strongest Crustle we can run locally:
`rule:crustle --deck-b crustle_v1`. It differs from `decks/crustle.py`, which is
the *field consensus* list mined from 2026-07-29 top episodes (seen 77x). Use
`crustle.py` to ask "what do we actually face" and `crustle_v1.py` to ask "how
bad is this matchup against a pilot that executes the lockdown". A pilot run on
the other list scores ~20 of its cards through a generic fallback, so it plays
them legally but badly -- worth remembering before reading a matchup number.
"""

from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # pragma: no cover
    from base import Deck  # noqa: F401


DECKLIST: dict[int, int] = {
    1: 19,   # Basic {G} Energy
    11: 4,   # Mist Energy
    14: 4,   # Spiky Energy
    18: 4,   # Grow Grass Energy
    344: 4,  # Dwebble
    345: 4,  # Crustle
    1086: 4, # Buddy-Buddy Poffin
    1147: 4, # Jumbo Ice Cream
    1212: 4, # Cook
    1224: 4, # Cheren
    1264: 4, # Battle Cage
    1159: 1, # Hero’s Cape
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, DECK.size
