"""Dragapult ex deck for the sample rule-based agent.

Auto-generated by scripts/import_rule_agents.py from
notebooks/a-sample-rule-based-agent-dragapult-ex-deck.ipynb -- the exact 60-card deck the
rule agent was tuned for (it hardcodes these card ids for card counting).
Do not hand-edit; re-run the importer instead.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/dragapult_ex.py`
    from base import Deck  # noqa: F401

Dreepy = 119
Drakloak = 120
Dragapult_ex = 121
Fezandipiti_ex = 140
Latias_ex = 184
Budew = 235
Meowth_ex = 1071
Rare_Candy = 1079
Unfair_Stamp = 1080
Buddy_Buddy_Poffin = 1086
Night_Stretcher = 1097
Crushing_Hammer = 1120
Ultra_Ball = 1121
Poke_Pad = 1152
Lucky_Helmet = 1156
Boss_Orders = 1182
Crispin = 1198
Brock_Scouting = 1210
Lillie_Determination = 1227
Team_Rocket_Watchtower = 1256
Basic_Fire_Energy = 2
Basic_Psychic_Energy = 5

DECKLIST: dict[int, int] = {
    Dreepy: 4,
    Drakloak: 4,
    Dragapult_ex: 3,
    Fezandipiti_ex: 1,
    Latias_ex: 1,
    Budew: 2,
    Meowth_ex: 1,
    Rare_Candy: 2,
    Unfair_Stamp: 1,
    Buddy_Buddy_Poffin: 4,
    Night_Stretcher: 2,
    Crushing_Hammer: 4,
    Ultra_Ball: 4,
    Poke_Pad: 3,
    Lucky_Helmet: 1,
    Boss_Orders: 3,
    Crispin: 4,
    Brock_Scouting: 2,
    Lillie_Determination: 4,
    Team_Rocket_Watchtower: 2,
    Basic_Fire_Energy: 4,
    Basic_Psychic_Energy: 4,
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {DECK.size}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{entry.count:>2}x  {entry.card.name}")
