"""Dragapult ex deck for the sample rule-based agent.

Auto-generated by scripts/import_rule_agents.py from
notebooks/a-sample-rule-based-agent-iono-s-deck.ipynb -- the exact 60-card deck the
rule agent was tuned for (it hardcodes these card ids for card counting).
Do not hand-edit; re-run the importer instead.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/iono.py`
    from base import Deck  # noqa: F401

Iono_Voltorb = 265
Iono_Tadbulb = 268
Iono_Bellibolt_ex = 269
Iono_Wattrel = 270
Iono_Kilowattrel = 271
Buddy_Buddy_Poffin = 1086
Night_Stretcher = 1097
Max_Rod = 1110
Energy_Retrieval = 1118
Ultra_Ball = 1121
Poke_Pad = 1152
Lillie_Determination = 1227
Canari = 1233
Levincia = 1254
Basic_Lightning_Energy = 4

DECKLIST: dict[int, int] = {
    Iono_Voltorb: 3,
    Iono_Tadbulb: 3,
    Iono_Bellibolt_ex: 3,
    Iono_Wattrel: 3,
    Iono_Kilowattrel: 3,
    Buddy_Buddy_Poffin: 3,
    Night_Stretcher: 2,
    Max_Rod: 1,
    Energy_Retrieval: 1,
    Ultra_Ball: 3,
    Poke_Pad: 2,
    Lillie_Determination: 4,
    Canari: 4,
    Levincia: 3,
    Basic_Lightning_Energy: 22,
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {DECK.size}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{entry.count:>2}x  {entry.card.name}")
