"""V10 baseline's Mega Lucario ex list (public LB 950+ notebook).

Auto-generated by scripts/import_v10_agent.py from
notebooks/strong-start-baseline-agent-v10-lb-950.ipynb. This is NOT the sample
agent's mega_lucario_ex list -- V10 retuned it, and the agent hardcodes these
card ids for counting. Do not hand-edit; re-run the importer.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/lucario_v10.py`
    from base import Deck  # noqa: F401

Basic_Fighting_Energy = 6
Boss_Orders = 1182
Carmine = 1192
Dusk_Ball = 1102
Fighting_Gong = 1142
Gravity_Mountain = 1252
Hariyama = 674
Hero_Cape = 1159
Lillie_Determination = 1227
Lunatone = 675
Makuhita = 673
Mega_Lucario_ex = 678
Poke_Pad = 1152
Premium_Power_Pro = 1141
Riolu = 677
Solrock = 676
Switch = 1123

DECKLIST: dict[int, int] = {
    Basic_Fighting_Energy: 14,
    Boss_Orders: 3,
    Carmine: 4,
    Dusk_Ball: 4,
    Fighting_Gong: 4,
    Gravity_Mountain: 1,
    Hariyama: 2,
    Hero_Cape: 1,
    Lillie_Determination: 4,
    Lunatone: 2,
    Makuhita: 2,
    Mega_Lucario_ex: 4,
    Poke_Pad: 2,
    Premium_Power_Pro: 4,
    Riolu: 4,
    Solrock: 3,
    Switch: 2,
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {DECK.size}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{entry.count:>2}x  {entry.card.name}")
