"""Dragapult ex deck for the sample rule-based agent.

Auto-generated by scripts/import_rule_agents.py from
notebooks/a-sample-rule-based-agent-mega-abomasnow-ex-deck.ipynb -- the exact 60-card deck the
rule agent was tuned for (it hardcodes these card ids for card counting).
Do not hand-edit; re-run the importer instead.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/mega_abomasnow_ex.py`
    from base import Deck  # noqa: F401

Kyogre = 721
Snover = 722
Mega_Abomasnow_ex = 723
Ultra_Ball = 1121
Precious_Trolley = 1126
Carmine = 1192
Lillie_Determination = 1227
Surfing_Beach = 1262
Basic_Water_Energy = 3

DECKLIST: dict[int, int] = {
    Kyogre: 2,
    Snover: 4,
    Mega_Abomasnow_ex: 4,
    Ultra_Ball: 4,
    Precious_Trolley: 1,
    Carmine: 4,
    Lillie_Determination: 4,
    Surfing_Beach: 3,
    Basic_Water_Energy: 34,
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {DECK.size}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{entry.count:>2}x  {entry.card.name}")
