"""Dragapult ex deck for the sample rule-based agent.

Auto-generated by scripts/import_rule_agents.py from
notebooks/a-sample-rule-based-agent-mega-lucario-ex-deck.ipynb -- the exact 60-card deck the
rule agent was tuned for (it hardcodes these card ids for card counting).
Do not hand-edit; re-run the importer instead.
"""
from __future__ import annotations

try:
    from .base import Deck
except ImportError:  # allow `python decks/mega_lucario_ex.py`
    from base import Deck  # noqa: F401

Makuhita = 673
Hariyama = 674
Lunatone = 675
Solrock = 676
Riolu = 677
Mega_Lucario_ex = 678
Dusk_Ball = 1102
Switch = 1123
Premium_Power_Pro = 1141
Fighting_Gong = 1142
Poke_Pad = 1152
Hero_Cape = 1159
Boss_Orders = 1182
Carmine = 1192
Lillie_Determination = 1227
Gravity_Mountain = 1252
Basic_Fighting_Energy = 6

DECKLIST: dict[int, int] = {
    Makuhita: 2,
    Hariyama: 2,
    Lunatone: 2,
    Solrock: 3,
    Riolu: 3,
    Mega_Lucario_ex: 4,
    Dusk_Ball: 4,
    Switch: 2,
    Premium_Power_Pro: 4,
    Fighting_Gong: 4,
    Poke_Pad: 4,
    Hero_Cape: 1,
    Boss_Orders: 2,
    Carmine: 4,
    Lillie_Determination: 4,
    Gravity_Mountain: 2,
    Basic_Fighting_Energy: 13,
}

DECK = Deck(DECKLIST)
assert DECK.size == 60, f"expected 60 cards, got {DECK.size}"


if __name__ == "__main__":
    print(DECK)
    for entry in DECK:
        print(f"{entry.count:>2}x  {entry.card.name}")
